try {
  let a = 2 + b
} catch(e) {
 console.log(e)
 //throw new Error(e)
} finally {
  console.log("Execut")
}

//console.log('Teste')